import { Plugin } from '../types';

export const PLUGINS: Plugin[] = [
  {
    id: 'geoai',
    name: 'GeoAI Country Guesser',
    description: 'An Akinator-inspired country guessing game powered by AI. Can you stump it?',
    command: '$g--geoai',
    url: 'https://geo-ai-eight-mu.vercel.app/',
    logoType: 'emoji',
    logoValue: '🌍',
    category: 'games',
    author: 'Rafsan1711',
    authorUrl: 'https://github.com/Rafsan1711/GeoAI',
    tags: ['ai', 'geography', 'guessing'],
    fullscreen: false,
  },
  {
    id: 'awg',
    name: 'AI Word Guess',
    description: 'A word guessing game with AI assistance. Test your vocabulary!',
    command: '$g--awg',
    url: 'https://rafsan1711.github.io/ai-word-guess/',
    logoType: 'fa',
    logoValue: 'spell-check',
    category: 'games',
    author: 'Rafsan1711',
    authorUrl: 'https://rafsan1711.github.io/ai-word-guess/',
    tags: ['word', 'puzzle', 'vocabulary'],
    fullscreen: false,
  },
  {
    id: 'dtb',
    name: 'Dots & Boxes',
    description: 'The classic Dots and Boxes strategy game. Challenge yourself!',
    command: '$g--dtb',
    url: 'https://rafsan1711.github.io/dot-and-box',
    logoType: 'url',
    logoValue: '/logos/dtb-logo.png',
    category: 'games',
    author: 'Rafsan1711',
    tags: ['strategy', 'classic', 'multiplayer'],
    fullscreen: false,
  },
  {
    id: 'bco',
    name: 'Battle Craft Odyssey',
    description: 'A Minecraft-inspired adventure and crafting game. Explore, build, survive!',
    command: '$g--bco',
    url: 'https://battle-craft-odyssey.vercel.app/',
    logoType: 'url',
    logoValue: '/logos/bco-logo.png',
    category: 'games',
    author: 'Rafsan1711',
    tags: ['minecraft', 'adventure', 'crafting', 'fullscreen'],
    fullscreen: true,
  },
  {
    id: 'pt3',
    name: '3D Periodic Table',
    description: 'An interactive 3D visualization of the Periodic Table of Elements. Science made beautiful.',
    command: '$t--pt3',
    url: 'https://periodic-table-3d-h3bb.onrender.com',
    logoType: 'emoji',
    logoValue: '⚛️',
    category: 'education',
    author: 'Rafsan1711',
    authorUrl: 'https://github.com/Rafsan1711/periodic-table-3d',
    tags: ['chemistry', '3d', 'science', 'periodic table'],
    fullscreen: false,
  },
  {
    id: 'sps',
    name: 'Sliding Puzzle Solver',
    description: 'Play the classic sliding puzzle — or watch the IDA* AI solve it instantly.',
    command: '$g--sps',
    url: 'https://rafsan1711.github.io/sliding-puzzle-with-Solver-IDA-/',
    logoType: 'fa',
    logoValue: 'puzzle-piece',
    category: 'games',
    author: 'Rafsan1711',
    tags: ['puzzle', 'ai', 'algorithm', 'ida*'],
    fullscreen: false,
  },
  {
    id: 'cat',
    name: 'Chess Analysis Tool',
    description: 'Analyze chess positions and matches with engine evaluation and move suggestions.',
    command: '$--cat',
    url: 'https://rafsan1711.github.io/analysis-chess/',
    logoType: 'fa',
    logoValue: 'chess-knight',
    category: 'tools',
    author: 'Rafsan1711',
    tags: ['chess', 'analysis', 'engine'],
    fullscreen: false,
  },
];
